import {createRequire} from 'node:module';import fs from 'node:fs/promises';import path from 'node:path';import assert from 'node:assert/strict';import {execFileSync} from 'node:child_process';
const require=createRequire(import.meta.url);const {chromium}=require('playwright');
const out=path.resolve(process.env.ARTIFACTS_DIR||'artifacts/browser');await fs.mkdir(out,{recursive:true});const base=process.env.APP_URL||'http://127.0.0.1:4173';
const browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_PATH||undefined,chromiumSandbox:true});const ctx=await browser.newContext({viewport:{width:1440,height:1100},acceptDownloads:true});const page=await ctx.newPage();const errors=[],checks=[];page.on('pageerror',e=>errors.push(e.message));
async function check(name,fn){await fn();checks.push(name);console.log('PASS',name);}
const ready=()=>page.waitForFunction(()=>document.querySelector('#download-usda').disabled===false);
async function reset(){await page.locator('#reset').click();await ready();}
async function download(button,filename){const pending=page.waitForEvent('download');await page.locator(button).click();const d=await pending;assert.equal(d.suggestedFilename(),filename);await d.saveAs(path.join(out,filename));assert.equal(await d.failure(),null);}
try{
 await page.goto(base);await ready();
 await check('Japanese initial sample and five exact edits',async()=>{assert.equal(await page.locator('html').getAttribute('lang'),'ja');assert.deepEqual(await page.locator('.stat b').allTextContents(),['5','2','2']);assert.equal(await page.locator('.path-row').count(),4);});
 await check('default scene tree and selected prim',async()=>{assert.equal(await page.locator('.tree-row').count(),4);assert.match(await page.locator('.tree-row.selected').innerText(),/Old/);});
 await check('preserved lookalike string and comment',async()=>{assert.equal(await page.locator('.untouched-row').count(),3);assert.match(await page.locator('#untouched').innerText(),/OldSpare/);});
 await check('download repaired USDA through browser',()=>download('#download-usda','repaired.usda'));
 await check('download hash-bound receipt through browser',()=>download('#download-receipt','rename-receipt.json'));
 await check('download complete coverage through browser',()=>download('#download-coverage','variant-coverage.json'));
 await check('coverage download contains every selection and source hash',async()=>{const report=JSON.parse(await fs.readFile(path.join(out,'variant-coverage.json'),'utf8'));const receipt=JSON.parse(await fs.readFile(path.join(out,'rename-receipt.json'),'utf8'));assert.equal(report.sourceHash,receipt.sourceHash);assert.equal(report.outputHash,receipt.outputHash);assert.deepEqual(report.selections.map(x=>Object.values(x.selection)[0]),['A','B']);});
 await page.screenshot({path:path.join(out,'desktop-ja.png'),fullPage:true});
 await page.locator('#language').click();await check('English preserves state and localizes controls',async()=>{assert.equal(await page.locator('html').getAttribute('lang'),'en');assert.equal(await page.locator('#review').innerText(),'Review rename');assert.deepEqual(await page.locator('.stat b').allTextContents(),['5','2','2']);});
 await page.screenshot({path:path.join(out,'desktop-en.png'),fullPage:true});
 await page.pdf({path:path.join(out,'review-print.pdf'),format:'A4',printBackground:true});
 await check('invalid rename immediately makes export stale',async()=>{await page.locator('#new-name').fill('Other');assert.equal(await page.locator('#download-usda').isDisabled(),true);assert.equal(await page.locator('#review-state').innerText(),'Review needed');});
 await check('review uses latest request after rapid edits',async()=>{await page.locator('#new-name').fill('Thing');await page.locator('#review').click();await page.locator('#new-name').fill('Handle');await page.locator('#review').click();await ready();assert.match(await page.locator('.after').first().innerText(),/Handle/);});
 await check('same-name request rejected',async()=>{await page.locator('#new-name').fill('Old');await page.locator('#review').click();await page.waitForFunction(()=>document.querySelector('#status').textContent.includes('REPEATED'));assert.equal(await page.locator('#download-usda').isDisabled(),true);});
 for(const [value,code] of [['collision','COLLISION'],['relative','PATH'],['reference','UNSUPPORTED'],['nested','NESTED_VARIANT']])await check(`${value} blocked with no export`,async()=>{await page.locator('#blocked-case').selectOption(value);await page.locator('#load-case').click();await page.waitForFunction(c=>document.querySelector('#status').textContent.includes(c),code);assert.equal(await page.locator('#download-usda').isDisabled(),true);});
 await page.screenshot({path:path.join(out,'blocked-case.png'),fullPage:true});
 await check('reset recovers blocked case',async()=>{await reset();assert.equal(await page.locator('#filename').innerText(),'product.usda');assert.deepEqual(await page.locator('.stat b').allTextContents(),['5','2','2']);});
 await check('source inspector opens and closes without mutation',async()=>{await page.locator('#edit-toggle').click();assert.equal(await page.locator('#source-editor').isVisible(),true);await page.locator('#edit-toggle').click();assert.equal(await page.locator('#source-editor').isVisible(),false);assert.equal(await page.locator('#download-usda').isDisabled(),false);});
 await check('UTF-8 USDA file import reviews actual file',async()=>{await page.locator('#file').setInputFiles('fixtures/product.usda');await ready();assert.equal(await page.locator('.path-row').count(),4);});
 await check('saved receipt replays only matching source',async()=>{const pending=page.waitForEvent('download');await page.locator('#receipt-file').setInputFiles(path.join(out,'rename-receipt.json'));const d=await pending;await d.saveAs(path.join(out,'receipt-replay.usda'));assert.equal(await fs.readFile(path.join(out,'receipt-replay.usda'),'utf8'),await fs.readFile(path.join(out,'repaired.usda'),'utf8'));});
 await check('source edit invalidates receipt and stale replay is rejected',async()=>{await page.locator('#edit-toggle').click();await page.locator('#source-editor').fill((await page.locator('#source-editor').inputValue())+'\n');assert.equal(await page.locator('#download-usda').isDisabled(),true);await page.locator('#receipt-file').setInputFiles(path.join(out,'rename-receipt.json'));await page.waitForFunction(()=>document.querySelector('#receipt-status').textContent.includes('STALE'));});
 await check('repeated receipt against repaired source is rejected',async()=>{await page.locator('#file').setInputFiles(path.join(out,'repaired.usda'));await page.locator('#receipt-file').setInputFiles(path.join(out,'rename-receipt.json'));await page.waitForFunction(()=>document.querySelector('#receipt-status').textContent.includes('REPEATED'));});
 await reset();await page.locator('#edit-toggle').click();
 await check('binary file rejected',async()=>{await page.locator('#file').setInputFiles({name:'binary.usdc',mimeType:'application/octet-stream',buffer:Buffer.from('PXR-USDC')});await page.waitForFunction(()=>document.querySelector('#status').classList.contains('error'));assert.equal(await page.locator('#download-usda').isDisabled(),true);});
 await reset();
 await check('invalid UTF-8 file rejected',async()=>{await page.locator('#file').setInputFiles({name:'invalid.usda',mimeType:'application/octet-stream',buffer:Buffer.from([0xff,0xfe])});await page.waitForFunction(()=>document.querySelector('#status').classList.contains('error'));assert.equal(await page.locator('#download-usda').isDisabled(),true);});
 await reset();
 await check('BOM import rejected without falsifying source hash',async()=>{await page.locator('#file').setInputFiles({name:'bom.usda',mimeType:'text/plain',buffer:Buffer.concat([Buffer.from([0xef,0xbb,0xbf]),await fs.readFile('fixtures/product.usda')])});await page.waitForFunction(()=>document.querySelector('#status').textContent.includes('FORMAT'));assert.equal(await page.locator('#download-usda').isDisabled(),true);});
 await reset();
 await check('source picker works by keyboard with visible focus',async()=>{await page.locator('#open-file').focus();const pending=page.waitForEvent('filechooser');await page.keyboard.press('Enter');await (await pending).setFiles('fixtures/product.usda');await ready();await page.locator('#open-file').focus();assert.equal(await page.locator('#open-file').evaluate(e=>e.matches(':focus-visible')),true);const outline=await page.locator('#open-file').evaluate(e=>getComputedStyle(e).outlineWidth);assert.notEqual(outline,'0px');});
 await check('receipt picker works by keyboard',async()=>{await page.locator('.receipt-tools').evaluate(e=>e.open=true);await page.locator('#open-receipt').focus();const chooser=page.waitForEvent('filechooser');await page.keyboard.press('Enter');const dl=page.waitForEvent('download');await (await chooser).setFiles(path.join(out,'rename-receipt.json'));await (await dl).saveAs(path.join(out,'keyboard-replay.usda'));});
 await page.setViewportSize({width:390,height:844});await check('mobile English has no horizontal overflow',async()=>assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true));await page.screenshot({path:path.join(out,'mobile-en.png'),fullPage:true});
 await page.locator('#language').click();await check('mobile Japanese has no horizontal overflow',async()=>assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true));await page.screenshot({path:path.join(out,'mobile-ja.png'),fullPage:true});
 await page.setViewportSize({width:320,height:750});await check('320px narrow layout no horizontal overflow',async()=>assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true));
 await page.goto('file://'+path.resolve('dist/variant-mend.html'));await ready();await check('single-file offline build runs with no requests',async()=>{await page.route('**/*',r=>r.abort());await page.locator('#reset').click();await ready();assert.equal(await page.locator('.path-row').count(),4);});
 await check('offline download is identical',async()=>{const p=page.waitForEvent('download');await page.locator('#download-usda').click();await (await p).saveAs(path.join(out,'offline-repaired.usda'));assert.deepEqual(await fs.readFile(path.join(out,'offline-repaired.usda')),await fs.readFile(path.join(out,'repaired.usda')));});
 await check('zero JavaScript runtime errors',async()=>assert.deepEqual(errors,[]));
 const report={status:'pass',checks:checks.length,names:checks,browser:browser.version(),platform:process.platform,os:execFileSync('uname',['-a'],{encoding:'utf8'}).trim(),node:process.version,artifacts:'Screenshots, PDF, actual browser downloads; no USD rendering claim'};await fs.writeFile(path.join(out,'browser-report.json'),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report,null,2));
}finally{await browser.close();}
