import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs/promises';import os from 'node:os';import path from 'node:path';import {spawnSync} from 'node:child_process';
const root=new URL('../',import.meta.url);const script=await fs.readFile(new URL('scripts/build.mjs',root));
const template='<!doctype html><html><head><meta http-equiv="Content-Security-Policy" content="default-src \'none\'; script-src \'self\' \'unsafe-inline\'; style-src \'self\' \'unsafe-inline\'"><link rel="stylesheet" href="src/style.css"></head><body><script type="module" src="src/app.mjs"></script></body></html>';
async function fixture(fn){const dir=await fs.mkdtemp(path.join(os.tmpdir(),'variant-mend-build-'));try{await fs.mkdir(path.join(dir,'scripts'));await fs.mkdir(path.join(dir,'src'));await fs.writeFile(path.join(dir,'scripts/build.mjs'),script);await fs.writeFile(path.join(dir,'index.html'),template);await fs.writeFile(path.join(dir,'src/style.css'),'body{color:#123}');await fs.writeFile(path.join(dir,'src/core.mjs'),'export const helper = 1;\n');await fs.writeFile(path.join(dir,'src/sample.mjs'),'export const SAMPLE = "sample";\n');await fs.writeFile(path.join(dir,'src/app.mjs'),"import {helper} from './core.mjs';\nconsole.log(SAMPLE);\n");await fn(dir);}finally{await fs.rm(dir,{recursive:true,force:true});}}
const run=dir=>spawnSync(process.execPath,['scripts/build.mjs'],{cwd:dir,encoding:'utf8'});
const read=dir=>fs.readFile(path.join(dir,'dist/variant-mend.html'),'utf8');
const extract=html=>html.match(/<script type="module">([\s\S]*?)<\/script>/)[1];
test('standalone build preserves every JavaScript replacement-dollar sequence',()=>fixture(async dir=>{const literal="$$ $& $` $'";await fs.writeFile(path.join(dir,'src/core.mjs'),'export const $$ = '+JSON.stringify(literal)+';\n');await fs.writeFile(path.join(dir,'src/app.mjs'),'console.log($$);\n');const result=run(dir);assert.equal(result.status,0,result.stderr);const inline=extract(await read(dir));assert.ok(inline.includes('const $$ = '+JSON.stringify(literal)));const executed=spawnSync(process.execPath,['--input-type=module'],{input:inline,encoding:'utf8'});assert.equal(executed.status,0,executed.stderr);assert.equal(executed.stdout.trim(),literal);}));
test('standalone build escapes literal closing script text without changing its value',()=>fixture(async dir=>{const literal='before </script> and </SCRIPT> after';await fs.writeFile(path.join(dir,'src/sample.mjs'),'export const SAMPLE = '+JSON.stringify(literal)+';\n');const result=run(dir);assert.equal(result.status,0,result.stderr);const html=await read(dir);assert.equal((html.match(/<\/script>/gi)||[]).length,1);const executed=spawnSync(process.execPath,['--input-type=module'],{input:extract(html),encoding:'utf8'});assert.equal(executed.status,0,executed.stderr);assert.equal(executed.stdout.trim(),literal);}));
test('standalone build rejects malformed generated module before writing',()=>fixture(async dir=>{await fs.writeFile(path.join(dir,'src/app.mjs'),'const malformed = ;');const result=run(dir);assert.notEqual(result.status,0);assert.match(result.stderr,/Standalone module syntax check failed/);await assert.rejects(fs.access(path.join(dir,'dist/variant-mend.html')));}));
test('standalone build rejects missing placeholders instead of silently incomplete output',()=>fixture(async dir=>{await fs.writeFile(path.join(dir,'index.html'),template.replace('<script type="module" src="src/app.mjs"></script>',''));const result=run(dir);assert.notEqual(result.status,0);assert.match(result.stderr,/Expected exactly one standalone build placeholder/);}));
test('actual app standalone module is syntax-valid and retains CSP without external module dependencies',()=>fixture(async dir=>{for(const name of ['index.html','src/core.mjs','src/sample.mjs','src/app.mjs','src/style.css'])await fs.writeFile(path.join(dir,name),await fs.readFile(new URL(name,root)));const result=run(dir);assert.equal(result.status,0,result.stderr);const html=await read(dir);const inline=extract(html);assert.match(inline,/const \$=s=>document\.querySelector\(s\), \$\$=s=>/);assert.equal((html.match(/<script\b/g)||[]).length,1);assert.ok(!html.includes('src="src/app.mjs"'));assert.ok(!/^import /m.test(inline));const source=await fs.readFile(new URL('index.html',root),'utf8');assert.equal(html.match(/<meta http-equiv="Content-Security-Policy"[^>]+>/)[0],source.match(/<meta http-equiv="Content-Security-Policy"[^>]+>/)[0]);}));
