import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs/promises';import os from 'node:os';import path from 'node:path';import {spawnSync} from 'node:child_process';
const cli=path.resolve('scripts/cli.mjs');const sample=await fs.readFile('fixtures/product.usda');
async function temporary(fn){const dir=await fs.mkdtemp(path.join(os.tmpdir(),'variant-mend-cli-test-'));try{await fn(dir);}finally{await fs.rm(dir,{recursive:true,force:true});}}
const run=(dir,source='input.usda',output='repaired.usda',receipt='receipt.json')=>spawnSync(process.execPath,[cli,source,'/Product/Old','Handle',output,receipt],{cwd:dir,encoding:'utf8'});
test('CLI rejects invalid UTF-8 without producing artifacts',()=>temporary(async dir=>{await fs.writeFile(path.join(dir,'input.usda'),Buffer.concat([sample,Buffer.from('# bad '),Buffer.from([255]),Buffer.from('\n')]));const result=run(dir);assert.equal(result.status,1);assert.equal(JSON.parse(result.stderr).code,'ENCODING');assert.deepEqual(await fs.readdir(dir),['input.usda']);}));
test('CLI bare output filenames work without stray directories',()=>temporary(async dir=>{await fs.writeFile(path.join(dir,'input.usda'),sample);const result=run(dir);assert.equal(result.status,0,result.stderr);assert.deepEqual((await fs.readdir(dir)).sort(),['input.usda','receipt.json','repaired.usda']);}));
test('CLI creates both separate output parent directories',()=>temporary(async dir=>{await fs.writeFile(path.join(dir,'input.usda'),sample);const result=run(dir,'input.usda','exports/repaired.usda','evidence/receipt.json');assert.equal(result.status,0,result.stderr);assert.ok((await fs.stat(path.join(dir,'evidence/receipt.json'))).isFile());}));
test('CLI rejects BOM rather than silently changing source hash',()=>temporary(async dir=>{await fs.writeFile(path.join(dir,'input.usda'),Buffer.concat([Buffer.from([239,187,191]),sample]));const result=run(dir);assert.equal(result.status,1);assert.equal(JSON.parse(result.stderr).code,'FORMAT');}));
test('CLI rejects in-place output',()=>temporary(async dir=>{await fs.writeFile(path.join(dir,'input.usda'),sample);const result=run(dir,'input.usda','input.usda');assert.equal(result.status,1);assert.equal(JSON.parse(result.stderr).code,'DESTINATION');assert.deepEqual(await fs.readFile(path.join(dir,'input.usda')),sample);}));
test('CLI rejects ambiguous output and receipt destination',()=>temporary(async dir=>{await fs.writeFile(path.join(dir,'input.usda'),sample);const result=run(dir,'input.usda','same.json','same.json');assert.equal(result.status,1);assert.equal(JSON.parse(result.stderr).code,'DESTINATION');}));

test('CLI rejects symlink output alias of input',()=>temporary(async dir=>{await fs.writeFile(path.join(dir,'input.usda'),sample);await fs.symlink('input.usda',path.join(dir,'repaired.usda'));const result=run(dir);assert.equal(result.status,1);assert.equal(JSON.parse(result.stderr).code,'DESTINATION');assert.deepEqual(await fs.readFile(path.join(dir,'input.usda')),sample);}));
test('CLI rejects hardlink receipt alias of input',()=>temporary(async dir=>{await fs.writeFile(path.join(dir,'input.usda'),sample);await fs.link(path.join(dir,'input.usda'),path.join(dir,'receipt.json'));const result=run(dir);assert.equal(result.status,1);assert.equal(JSON.parse(result.stderr).code,'DESTINATION');assert.deepEqual(await fs.readFile(path.join(dir,'input.usda')),sample);}));
test('CLI rejects output/receipt aliases',()=>temporary(async dir=>{await fs.writeFile(path.join(dir,'input.usda'),sample);await fs.writeFile(path.join(dir,'repaired.usda'),'old export');await fs.link(path.join(dir,'repaired.usda'),path.join(dir,'receipt.json'));const result=run(dir);assert.equal(result.status,1);assert.equal(JSON.parse(result.stderr).code,'DESTINATION');assert.equal(await fs.readFile(path.join(dir,'repaired.usda'),'utf8'),'old export');}));

test('CLI rejects oversized input before reading its bytes',()=>temporary(async dir=>{const handle=await fs.open(path.join(dir,'input.usda'),'w');await handle.truncate(10*1024*1024);await handle.close();const result=run(dir);assert.equal(result.status,1);assert.equal(JSON.parse(result.stderr).code,'SIZE');assert.deepEqual(await fs.readdir(dir),['input.usda']);}));
test('CLI rejects nonregular input before reading',()=>temporary(async dir=>{await fs.mkdir(path.join(dir,'input.usda'));const result=run(dir);assert.equal(result.status,1);assert.equal(JSON.parse(result.stderr).code,'FORMAT');}));
