import {analyze,applyReceipt,parse} from './core.mjs';
import {SAMPLE} from './sample.mjs';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const translations={
 en:{local:'Processed on this device',eyebrow:'A SMALLER, SAFER HANDOFF',headline:'Rename the prim.<br>Keep the connections.',lead:'Review unselected variants, too. Repair one prim name and its matching paths in a single USDA file.',profile:'A deliberately small repair',profileText:'Same-parent rename · Absolute paths only<br>Up to 32 flat-variant combinations',boundariesLink:'See the supported profile ↗',source:'Source',import:'Open USDA',reset:'Reset sample',editSource:'Inspect source',sourceText:'USDA source',sceneTree:'Scene structure',selectedPrim:'Prim to rename',treeNote:'Variant-authored paths are reviewed in the inventory on the right.',rename:'Review the change',oldPath:'Current prim path',newName:'New sibling name',review:'Review rename',pathInventory:'Path changes',untouched:'Preserved as written',handoff:'REVIEWED HANDOFF',exportTitle:'A repair with its own paper trail.',exportText:'Record the source SHA-256 and exact edit positions. Export only the change you reviewed.',receiptTools:'Verify and apply a saved receipt',loadReceipt:'Open receipt',knownLimits:'KNOW THE BOUNDARY',limitsTitle:'Stop where the scope stops.',limitsText:'USDC / USDZ, external references, payloads, sublayers, relative paths, nested variants, instances, and reparenting are outside this profile.',consumerNote:'This screen runs bounded grammar and structural checks. The included sample is verified separately with usd-core 26.8. General USD composition or render equivalence is not guaranteed.',tryBlocked:'Try a rejected case',chooseCase:'Select a case',collisionCase:'Existing sibling collision',relativeCase:'Relative path',referenceCase:'External reference',nestedCase:'Nested variant',loadCase:'Load into sample',footer:'No upload · No runtime SDK · Works offline',ready:'Ready to export',stale:'Review needed',readyMessage:'Exact-span repair ready. All supported variant combinations covered.',staleMessage:'Source or request changed. Review again before exporting.',changes:'exact edits',combinations:'variant combinations',inert:'inert text preserved',base:'base scene',noPaths:'No matching relationship or connection paths',path:'path',string:'string',comment:'comment',receiptOk:'Receipt verified. Repaired USDA downloaded.',sampleReset:'Sample restored',unsupportedFile:'Open one .usda file, up to 1 MiB',receiptStale:'The source no longer matches this receipt'},
 ja:{ready:'書き出し可能',stale:'再確認が必要',readyMessage:'編集位置を確定しました。対応する全 variant の組み合わせを確認済みです。',staleMessage:'ソースまたは条件が変わりました。書き出す前に再確認してください。',changes:'編集する位置',combinations:'variant の組み合わせ',inert:'そのまま残すテキスト',base:'base scene',noPaths:'変更対象の relationship / connection はありません',path:'path',string:'文字列',comment:'コメント',receiptOk:'receipt の照合完了。修復済み USDA を書き出しました。',unsupportedFile:'1 MiB 以下の .usda ファイルを選んでください'}
};
$$('[data-t]').forEach(el=>{translations.ja[el.dataset.t]=el.innerHTML;});
let lang='ja',current=null,revision=0,source=SAMPLE,filename='product.usda';
const t=key=>translations[lang][key]??translations.en[key]??key;
const errorJa={TYPE:'prim の型は英大文字で始まる識別名を指定してください',FORMAT:'UTF-8 の USDA テキストだけを扱えます',SIZE:'サイズ上限を超えています',ENCODING:'文字コードが不正です',PATH:'絶対パスの対応形式だけを扱えます',UNSUPPORTED:'対応していない構文が含まれます',SYNTAX:'対応文法として解釈できません',STRING:'対応していない文字列形式です',NAME:'通常の識別名を指定してください',METADATA:'対応していないメタデータです',VARIANT:'variant の宣言と初期選択を確認してください',COVERAGE:'variant の検証上限を超えています',PROPERTY:'対応していないプロパティ形式です',VALUE:'値の形式が不正です',DUPLICATE:'同じ宣言が重複しています',NESTED_VARIANT:'nested variant は対象外です',TARGET:'variant 外の非ルート prim を指定してください',COLLISION:'変更先に同名の prim があります',REPEATED:'すでに適用済み、または同じ名前です',STALE:'ソースが receipt の元データと一致しません',RECEIPT:'receipt の内容が照合結果と一致しません',UNRESOLVED:'いずれかの variant で参照先が見つかりません',CONNECTION:'connection にはプロパティの絶対パスが必要です',SEPARATOR:'文の区切りに改行が必要です',DEPTH:'ネストの上限を超えています',TOKENS:'トークンの上限を超えています',EMPTY:'prim がありません',DEFAULT:'defaultPrim を確認してください'};
const errorText=e=>`${e.code??'ERROR'} · ${lang==='ja'&&errorJa[e.code]?errorJa[e.code]+' / ':''}${e.message}`;
$('#source-editor').value=source;
function invalidate(){revision++;current=null;$$('.export-actions button').forEach(b=>b.disabled=true);$('#review-state').textContent=t('stale');$('#status').className='';$('#status').textContent=t('staleMessage');$('#receipt-status').textContent='';$('#summary').replaceChildren();$('#inventory').replaceChildren();$('#untouched').replaceChildren();$('#preserved-count').textContent='0';$('#coverage-count').textContent='';renderTree();}
function node(tag,className,text){const e=document.createElement(tag);e.className=className;if(text!==undefined)e.textContent=text;return e;}
function renderTree(model){let prims=[];try{prims=(model??parse(source)).prims;}catch{}const tree=$('#tree');tree.replaceChildren();for(const p of prims){const row=node('div','tree-row'+(p.path===$('#old-path').value?' selected':''));row.style.paddingLeft=(9+(p.path.split('/').length-2)*14)+'px';row.append(node('span','glyph',p.path.split('/').length===2?'◇':'└'),node('span','',p.name));if(Object.keys(p.context).length)row.append(node('small','',Object.values(p.context).join('/')));tree.append(row);}}
function draw(result){renderTree(result.model);$('#review-state').textContent=t('ready');$('#status').className='';$('#status').textContent=t('readyMessage');$('#summary').replaceChildren();for(const [value,key] of [[result.receipt.edits.length,'changes'],[result.coverage.length,'combinations'],[result.inert.length,'inert']]){const stat=node('div','stat');stat.append(node('b','',value),node('span','',t(key)));$('#summary').append(stat);}$('#coverage-count').textContent=result.coverage.length+'/'+result.coverage.length+' covered';const groups=new Map();for(const path of result.affected){const context=Object.entries(path.context).map(([k,v])=>k.split(':').at(-1)+' = '+v).join(' · ')||t('base');if(!groups.has(context))groups.set(context,[]);groups.get(context).push(path);}$('#inventory').replaceChildren();for(const [context,paths] of groups){const group=node('div','variant-group');group.append(node('div','variant-heading',context));for(const p of paths){const row=node('div','path-row');row.append(node('span','kind',p.kind==='relationship'?'RELATIONSHIP':'CONNECTION'));const diff=node('div','path-diff');diff.append(node('span','before',p.value),node('i','','→'),node('span','after',p.next));row.append(diff);group.append(row);}$('#inventory').append(group);}if(!groups.size)$('#inventory').append(node('div','empty-state',t('noPaths')));
 $('#untouched').replaceChildren();const preserved=[...result.untouched.map(x=>({kind:'path',value:x.value})),...result.inert.map(x=>({kind:x.value.startsWith('#')?'comment':'string',value:x.value}))];for(const p of preserved){const row=node('div','untouched-row');row.append(node('span','',t(p.kind)),node('span','',p.value));$('#untouched').append(row);}$('#preserved-count').textContent=preserved.length;$$('.export-actions button').forEach(b=>b.disabled=false);
}
async function review(){const token=++revision;current=null;$$('.export-actions button').forEach(b=>b.disabled=true);try{const result=await analyze(source,$('#old-path').value.trim(),$('#new-name').value.trim());if(token!==revision)return;current=result;draw(result);}catch(e){if(token!==revision)return;$('#status').className='error';$('#status').textContent=errorText(e);$('#review-state').textContent=t('stale');$('#summary').replaceChildren();$('#inventory').replaceChildren();$('#untouched').replaceChildren();$('#preserved-count').textContent='0';$('#coverage-count').textContent='';renderTree();}}
function download(text,name,type){const url=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1500);}
$('#review').addEventListener('click',review);
for(const id of ['old-path','new-name'])$('#'+id).addEventListener('input',invalidate);
$('#source-editor').addEventListener('input',()=>{source=$('#source-editor').value;invalidate();});
$('#edit-toggle').addEventListener('click',()=>{const next=$('#editor-wrap').hidden;$('#editor-wrap').hidden=!next;$('#edit-toggle').setAttribute('aria-expanded',String(next));});
$('#reset').addEventListener('click',()=>{source=SAMPLE;filename='product.usda';$('#filename').textContent=filename;$('#source-editor').value=source;$('#old-path').value='/Product/Old';$('#new-name').value='Handle';$('#file').value='';$('#receipt-file').value='';$('#blocked-case').value='';$('#receipt-status').textContent='';invalidate();review();});
$('#open-file').addEventListener('click',()=>$('#file').click());
$('#open-receipt').addEventListener('click',()=>$('#receipt-file').click());
$('#file').addEventListener('change',async e=>{const file=e.target.files[0];if(!file)return;invalidate();const token=revision;try{if(!file.name.toLowerCase().endsWith('.usda')||file.size>1048576)throw Error(t('unsupportedFile'));const bytes=await file.arrayBuffer();if(token!==revision)return;source=new TextDecoder('utf-8',{fatal:true,ignoreBOM:true}).decode(bytes);filename=file.name;$('#filename').textContent=filename;$('#source-editor').value=source;invalidate();await review();}catch(err){if(token!==revision)return;$('#status').className='error';$('#status').textContent=err.message;}});
$('#download-usda').addEventListener('click',async()=>{const result=current;if(!result)return;try{const output=await applyReceipt(source,result.receipt);if(current!==result)return;download(output,'repaired.usda','text/plain;charset=utf-8');}catch(e){invalidate();$('#status').className='error';$('#status').textContent=e.message;}});
$('#download-receipt').addEventListener('click',()=>{if(current)download(JSON.stringify(current.receipt,null,2)+'\n','rename-receipt.json','application/json');});
$('#download-coverage').addEventListener('click',()=>{if(current)download(JSON.stringify({schema:'variant-mend-coverage/1',sourceHash:current.receipt.sourceHash,outputHash:current.receipt.outputHash,selections:current.coverage,scope:current.receipt.validation},null,2)+'\n','variant-coverage.json','application/json');});
$('#receipt-file').addEventListener('change',async e=>{const file=e.target.files[0];if(!file)return;const token=revision;try{if(file.size>2097152)throw Error('Receipt exceeds 2 MiB');const receipt=JSON.parse(await file.text());const output=await applyReceipt(source,receipt);if(token!==revision)throw Error(t('receiptStale'));download(output,'repaired.usda','text/plain;charset=utf-8');$('#receipt-status').textContent=t('receiptOk');}catch(err){$('#receipt-status').textContent=errorText(err);}e.target.value='';});
$('#language').addEventListener('click',()=>{lang=lang==='ja'?'en':'ja';document.documentElement.lang=lang;$('#language').textContent=lang==='ja'?'EN':'JA';$('#language').setAttribute('aria-label',lang==='ja'?'Switch language to English':'日本語に切り替え');$$('[data-t]').forEach(el=>el.innerHTML=t(el.dataset.t));if(current)draw(current);else $('#review-state').textContent=t('stale');});
$('#load-case').addEventListener('click',()=>{const selected=$('#blocked-case').value;if(!selected)return;source=SAMPLE;$('#old-path').value='/Product/Old';$('#new-name').value='Handle';if(selected==='collision')$('#new-name').value='OldSpare';if(selected==='relative')source=source.replace('</Product/Old>','<Old>');if(selected==='reference')source=source.replace('prepend variantSets','prepend references = @asset.usda@\n prepend variantSets');if(selected==='nested')source=source.replace('"A" {','"A" {\n variantSet "inside" = { "x" {} }');$('#source-editor').value=source;filename=selected+'-blocked.usda';$('#filename').textContent=filename;invalidate();review();});
review();
